name=Mathmatics_tmj
version=1.0
author=Tomoji Kanae
maintainer=Tomoji Kanae <gmh39599@kwansei.ac.jp>
sentence=a math library
paragraph=Supports general mathematical operations in Arduino UNO and ESP32
category=Device Control
architectures=*